name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:test
    - name: Save the Docker image
      run: docker save -o image.tar my-image-name:test
    - name: Release the Docker image
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.osx }}
        body_path: ./CHANGELOG.md
        files: |
          ./build/**
          ./CHANGELOG.md
